global_options:
  build_web_compilers|ddc:
    options:
      environment:
        prod: false
  build_web_compilers|entrypoint:
    release_options:
      # https://dart.dev/tools/dart2js
      dart2js_args:
        - -Dprod=true
        - -O4
